name: Deploy Node Server

on:
    push:
        branches:
            - main
            - dev

jobs:
    # Build and push to Docker hub
    # build:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Checkout source
    #       uses: actions/checkout@v4
    #     - name: Create .env file
    #       run: |
    #         echo "NODE_ENV=${{secrets.NODE_ENV}}" >> .env
    #         echo "DEV_APP_PORT=${{secrets.DEV_APP_PORT}}" >> .env
    #         echo "DEV_SECRET_KEY=${{secrets.DEV_SECRET_KEY}}" >> .env
    #         echo "DEV_SECRET_KEY=${{secrets.DEV_CLIENT_TOKEN}}" >> .env

    #         echo "REDIS_HOST=${{secrets.REDIS_HOST}}" >> .env
    #         echo "REDIS_PORT=${{secrets.REDIS_PORT}}" >> .env

    #         echo `PROD_POSTGRES_HOST=${{secrets.PROD_POSTGRES_HOST}}` >> .env
    #         echo "PROD_POSTGRES_USER=${{secrets.PROD_POSTGRES_USER}}" >> .env
    #         echo "PROD_POSTGRES_PW=${{secrets.PROD_POSTGRES_PW}}" >> .env
    #         echo "PROD_POSTGRES_DB=${{secrets.PROD_POSTGRES_DB}}" >> .env
    #         echo "PROD_POSTGRES_PORT=${{secrets.PROD_POSTGRES_PORT}}" >> .env

    #         echo "PROD_REDIS_HOST=${{secrets.PROD_REDIS_HOST}}" >> .env
    #         echo "PROD_REDIS_PORT=${{secrets.PROD_REDIS_PORT}}" >> .env

    #         echo "PROD_RMQ_USER=${{secrets.PROD_RMQ_USER}}" >> .env
    #         echo "PROD_RMQ_PW=${{secrets.PROD_RMQ_PW}}" >> .env
    #         echo "PROD_RMQ_HOST=${{secrets.PROD_RMQ_HOST}}" >> .env

    #     - name: Login to docker hub
    #       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #     - name: Build docker image
    #       run: docker build -t duymt3/happyboard-be .
    #     - name: Publish image to docker hub
    #       run: docker push duymt3/happyboard-be:latest

    # Build and push iamge to ECR
    build:
        runs-on: ubuntu-latest
        steps:
            # 1. Checkout source code
            - name: Checkout code
              uses: actions/checkout@v3

            # 2. Set up AWS credentials
            - name: Set up AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
            
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              
            - name: Build, Tag, the Image to Amazon ECR
              id: build-image
              env: 
                ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
                ECR_REPOSITORY: public-repo
                IMAGE_TAG: latest
              run: |
                docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                docker push 
           
    # deploy:
    #   needs: build
    #   runs-on: cicd-be
    #   steps:
    #     - name: Pull image from docker hub
    #       run: docker pull duymt3/happyboard-be:latest
    #     - name: Delete old container
    #       run: docker rm -f happyboard-be-container
    #     - name: Delete old image
    #       run: docker rmi duymt3/happyboard-be:latest
    #     - name: Run docker container
    #       run: docker run -d -p 8000:8000 --name happyboard-be-container duymt3/happyboard-be:latest
