name: Deploy Node Server

on:
  push: 
    branches:
      - feature/cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo `NODE_ENV=${{secrets.NODE_ENV}}` >> .env
          echo "DEV_APP_PORT=${{secrets.DEV_APP_PORT}}" >> .env
          echo "DEV_SECRET_KEY=${{secrets.DEV_SECRET_KEY}}" >> .env
          echo "DEV_POSTGRES_HOST=${{secrets.DEV_POSTGRES_HOST}}" >> .env
          echo "DEV_POSTGRES_PW=${{secrets.DEV_POSTGRES_PW}}" >> .env
          echo "DEV_POSTGRES_DB=${{secrets.DEV_POSTGRES_DB}}" >> .env
          echo "DEV_POSTGRES_PORT=${{secrets.DEV_POSTGRES_PORT}}" >> .env
          echo "DEV_ES_CLOUDID=${{secrets.DEV_ES_CLOUDID}}" >> .env
          echo "DEV_ES_USER=${{secrets.DEV_ES_USER}}" >> .env
          echo "DEV_ES_PW=${{secrets.DEV_ES_PW}}" >> .env
          echo "DEV_ES_INDEX=${{secrets.DEV_ES_INDEX}}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}       
      - name: Build docker image
        run: docker build -t duymt3/happyboard-be .  
      - name: Publish image to docker hub
        run: docker push duymt3/happyboard-be:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull duymt3/happyboard-be:latest
      - name: Delete old container
        run: docker rm -f duymt3/happyboard-be-container
      - name: Run docker container
        run: docker run -d -p 8000:8000 --name happyboard-be-container duymt3/happyboard-be