name: Deploy Node Server

on:
    push:
        branches:
            - main
            - dev
jobs:
    # Build and push to Docker hub
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4
            - name: Create .env file
              run: |
                  echo "NODE_ENV=${{secrets.NODE_ENV}}" >> .env
                  echo "DOMAIN_CLIENT=${{secrets.DOMAIN_CLIENT}}" >> .env
                  echo "DOMAIN_ADMIN=${{secrets.DOMAIN_ADMIN}}" >> .env
                  echo "DOMAIN_RESET_PASSWORD=${{secrets.DOMAIN_RESET_PASSWORD}}" >> .env

                  echo "PORT=${{secrets.PORT}}" >> .env
                  echo "SECRET_KEY=${{secrets.SECRET_KEY}}" >> .env

                  echo `PROD_POSTGRES_HOST=${{secrets.PROD_POSTGRES_HOST}}` >> .env
                  echo "PROD_POSTGRES_USER=${{secrets.PROD_POSTGRES_USER}}" >> .env
                  echo "PROD_POSTGRES_PW=${{secrets.PROD_POSTGRES_PW}}" >> .env
                  echo "PROD_POSTGRES_DB=${{secrets.PROD_POSTGRES_DB}}" >> .env
                  echo "PROD_POSTGRES_PORT=${{secrets.PROD_POSTGRES_PORT}}" >> .env

                  echo "PROD_REDIS_URI=${{secrets.PROD_REDIS_URI}}" >> .env

                  echo "PROD_ES_NODE=${{secrets.PROD_ES_NODE}}" >> .env
                  echo "PROD_ES_USER=${{secrets.PROD_ES_USER}}" >> .env
                  echo "PROD_ES_PW=${{secrets.PROD_ES_PW}}" >> .env
                  echo "ES_INDEX=${{secrets.ES_INDEX}}" >> .env


                  echo "PROD_RMQ_HOST=${{secrets.PROD_RMQ_HOST}}" >> .env
                  echo "PROD_RMQ_USER=${{secrets.PROD_RMQ_USER}}" >> .env
                  echo "PROD_RMQ_PW=${{secrets.PROD_RMQ_PW}}" >> .env

                  echo "GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}" >> .env
                  echo "GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}" >> .env
                  echo "GOOGLE_CALL_BACK_URL=${{secrets.GOOGLE_CALL_BACK_URL}}" >> .env

                  echo "CLOUDINARY_CLOUD_NAME=${{secrets.CLOUDINARY_CLOUD_NAME}}" >> .env
                  echo "CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}}" >> .env
                  echo "CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}}" >> .env

                  echo "EMAIL_USERNAME=${{secrets.EMAIL_USERNAME}}" >> .env
                  echo "EMAIL_PASSWORD=${{secrets.EMAIL_PASSWORD}}" >> .env  
                  
                  echo "CLIENT_MAIL=${{secrets.CLIENT_MAIL}}" >> .env
                  echo "PRIVATE_KEY=${{secrets.PRIVATE_KEY}}" >> .env  

            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build docker image
              run: docker build -t duymt3/happyboard-be .
            - name: Publish image to docker hub
              run: docker push duymt3/happyboard-be:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Pull image from docker hub
              run: docker pull duymt3/happyboard-be:latest
            - name: Stop old container
              run: docker stop happyboard-be-container
            - name: Remove old container
              run: docker rm happyboard-be-container
            - name: Remove old image
              run: docker rmi duymt3/happyboard-be:latest
            - name: Run docker container
              run: docker run -d -p 8000:8000 --name happyboard-be-container duymt3/happyboard-be:latest
